SELECT * FROM COVIDDEATH
WHERE CONTINENT IS NOT NULL
ORDER BY LOCATION, DATEE;

-- Select data that we are going to be using
SELECT LOCATION
    , DATEE
    , TOTAL_CASES
    , NEW_CASES
    , TOTAL_DEATHS
    , POPULATION
FROM COVIDDEATH
ORDER BY LOCATION, DATEE;

-- TOTAL CASES vs. TOTAL DEATHS
-- May examine each country using WHERE CLAUSE
SELECT LOCATION
    , DATEE
    , COALESCE(TOTAL_CASES, 0) TOTAL_CASES
    , COALESCE(TOTAL_DEATHS, 0) TOTAL_DEATHS
    , COALESCE(ROUND(TOTAL_DEATHS/TOTAL_CASES * 100,2), 0) DEATH_PERCENTAGE
FROM COVIDDEATH
WHERE LOCATION LIKE '%Vietnam%'
ORDER BY LOCATION, DATEE;

-- TOTAL CASES vs. POPULATION
-- Shows what percentage of population got Covid
-- May examine each country using WHERE clause
SELECT LOCATION
    , DATEE
    , COALESCE(TOTAL_CASES, 0) TOTAL_CASES
    , COALESCE(POPULATION, 0) POPULATION
    , COALESCE(ROUND(TOTAL_CASES/POPULATION * 100,2), 20) DEATH_PERCENTAGE
FROM COVIDDEATH
WHERE LOCATION LIKE '%Vietnam%'
ORDER BY LOCATION, DATEE;

-- Countries with Highest Infection Rate compared to Population 

SELECT LOCATION
    , POPULATION
    , COALESCE(MAX(TOTAL_CASES), 0) HIGHEST_INFECTION_COUNT
    , COALESCE(ROUND(MAX(TOTAL_CASES/POPULATION)*100, 2), 0) PERCENT_POPULATION_INFECTED
FROM COVIDDEATH
GROUP BY LOCATION, POPULATION
ORDER BY PERCENT_POPULATION_INFECTED DESC;

-- Countries with Highest Death Count

SELECT LOCATION
    , COALESCE(MAX(TOTAL_DEATHS), 0) TOTAL_DEATH_COUNT
FROM COVIDDEATH
WHERE CONTINENT IS NOT NULL
GROUP BY LOCATION
ORDER BY TOTAL_DEATH_COUNT DESC;

-- Continent with Highest Death Count
SELECT LOCATION
    , COALESCE(MAX(TOTAL_DEATHS), 0) TOTAL_DEATH_COUNT
FROM COVIDDEATH
WHERE CONTINENT IS NULL
GROUP BY LOCATION
ORDER BY TOTAL_DEATH_COUNT DESC;

-- GLOBAL NUMBERS

SELECT
    SUM(NEW_CASES) TOTAL_CASES
    , SUM(NEW_DEATHS) TOTAL_DEATHS
    , ROUND(SUM(NEW_DEATHS)/SUM(NEW_CASES) * 100, 2) DEATH_PERCENTAGE
FROM COVIDDEATH
WHERE CONTINENT IS NOT NULL;

-- TOTAL POPULATION vs. VACCINATION

-- CREATE A VIEW FOR EASY REVIEWING
CREATE VIEW PERCENT_POPULATION_VACCINATED AS
    WITH T AS(
        SELECT C.CONTINENT, C.LOCATION, C.DATEE, C.POPULATION, V.NEW_VACCINATIONS
            , SUM(V.NEW_VACCINATIONS) OVER (PARTITION BY C.LOCATION ORDER BY C.LOCATION, C.DATEE) ROLLING_PEOPLE_VACCINATED
        FROM COVIDDEATH C
            JOIN VACCINATION V
                ON C.LOCATION = V.LOCATION
                    AND C.DATEE = V.DATEE
        WHERE C.CONTINENT IS NOT NULL
    --    ORDER BY C.LOCATION, C.DATEE
    )
    SELECT CONTINENT
        , LOCATION
        , DATEE
        , POPULATION
        , NEW_VACCINATIONS
        , ROLLING_PEOPLE_VACCINATED
        , ROUND((ROLLING_PEOPLE_VACCINATED/POPULATION) * 100, 2) PEOPLE_VACCINATED_PER_POPULATION
    FROM T;
    
SELECT * FROM PERCENT_POPULATION_VACCINATED;
