-- Standardize Date Format
SELECT SALEDATE, TO_DATE(SALEDATE, 'YYYY-MM-DD')
FROM NASHVILLEHOUSING;

ALTER TABLE NASHVILLEHOUSING
ADD SALEDATECONVERTED DATE;

UPDATE NASHVILLEHOUSING
SET SALEDATECONVERTED = TO_DATE(SALEDATE, 'YYYY-MM-DD');

SELECT SALEDATE, SALEDATECONVERTED
FROM NASHVILLEHOUSING;

-------------------------------------------------------------------------------

-- Populate Property Address data

SELECT *
FROM NASHVILLEHOUSING
--WHERE PROPERTYADDRESS IS NULL
ORDER BY PARCELID;

SELECT N1.PARCELID, N1.PROPERTYADDRESS, N2.PARCELID, N2.PROPERTYADDRESS, COALESCE(N1.PROPERTYADDRESS, N2.PROPERTYADDRESS)
FROM NASHVILLEHOUSING N1
    JOIN NASHVILLEHOUSING N2
        ON N1.PARCELID = N2.PARCELID
            AND N1.UNIQUEID_ <> N2.UNIQUEID_
WHERE N1.PROPERTYADDRESS IS NULL;


UPDATE NASHVILLEHOUSING N1
SET N1.PROPERTYADDRESS = (
    SELECT DISTINCT N2.PROPERTYADDRESS 
    FROM NASHVILLEHOUSING N2
    WHERE 1=1
        AND N1.PARCELID = N2.PARCELID 
        AND N1.UNIQUEID_<> N2.UNIQUEID_ 
        AND N2.PROPERTYADDRESS IS NOT NULL
    FETCH FIRST 1 ROW ONLY
)
WHERE N1.PROPERTYADDRESS IS NULL;

-------------------------------------------------------------------------------

-- Breaking out Address into Individual Column (Address, City, State)
SELECT PROPERTYADDRESS
FROM NASHVILLEHOUSING;

SELECT 
    SUBSTR(PROPERTYADDRESS, 1, INSTR(PROPERTYADDRESS, ',')-1) ADDRESS
    , SUBSTR(PROPERTYADDRESS, INSTR(PROPERTYADDRESS, ',') + 1, LENGTH(PROPERTYADDRESS)) CITY
FROM NASHVILLEHOUSING;

ALTER TABLE NASHVILLEHOUSING
ADD PROPERTYSPLITADDRESS VARCHAR(255);

UPDATE NASHVILLEHOUSING
SET PROPERTYSPLITADDRESS = SUBSTR(PROPERTYADDRESS, 1, INSTR(PROPERTYADDRESS, ',')-1);

ALTER TABLE NASHVILLEHOUSING
ADD PROPERTYSPLITCITY VARCHAR(255);

UPDATE NASHVILLEHOUSING
SET PROPERTYSPLITCITY = SUBSTR(PROPERTYADDRESS, INSTR(PROPERTYADDRESS, ',') + 1, LENGTH(PROPERTYADDRESS));

SELECT OWNERADDRESS FROM NASHVILLEHOUSING;

SELECT REGEXP_SUBSTR(OWNERADDRESS, '[^,]+', 1, 1) AS ADDRESS
       , REGEXP_SUBSTR(OWNERADDRESS, '[^,]+', 1, 2) AS CITY
       , REGEXP_SUBSTR(OWNERADDRESS, '[^,]+', 1, 3) AS STATE
FROM NASHVILLEHOUSING;

ALTER TABLE NASHVILLEHOUSING
ADD OWNERSPLITADDRESS VARCHAR(255);

UPDATE NASHVILLEHOUSING
SET OWNERSPLITADDRESS = REGEXP_SUBSTR(OWNERADDRESS, '[^,]+', 1, 1);

ALTER TABLE NASHVILLEHOUSING
ADD OWNERSPLITCITY VARCHAR(255);

UPDATE NASHVILLEHOUSING
SET OWNERSPLITCITY = REGEXP_SUBSTR(OWNERADDRESS, '[^,]+', 1, 1);

ALTER TABLE NASHVILLEHOUSING
ADD OWNERSPLITSTATE VARCHAR(255);

UPDATE NASHVILLEHOUSING
SET OWNERSPLITSTATE = REGEXP_SUBSTR(OWNERADDRESS, '[^,]+', 1, 1);

-------------------------------------------------------------------------------

-- Change Y and N to Yes and No in "Sold as Vacant" Field
SELECT 
    SOLDASVACANT,
    CASE 
        WHEN SOLDASVACANT = 'Y' THEN 'Yes'
        WHEN SOLDASVACANT = 'N' THEN 'No'
        ELSE SOLDASVACANT
    END SOLDCHANGE
FROM NASHVILLEHOUSING;

UPDATE NASHVILLEHOUSING
SET SOLDASVACANT = CASE 
        WHEN SOLDASVACANT = 'Y' THEN 'Yes'
        WHEN SOLDASVACANT = 'N' THEN 'No'
        ELSE SOLDASVACANT
    END;

-------------------------------------------------------------------------------

-- Remove Duplicates
CREATE VIEW T AS(
    SELECT NASHVILLEHOUSING.*, ROW_NUMBER() OVER (
        PARTITION BY PARCELID
            , PROPERTYADDRESS
            , SALEPRICE
            , SALEDATE
            , LEGALREFERENCE 
        ORDER BY UNIQUEID_) ROW_NUM
    FROM NASHVILLEHOUSING
);
DELETE TABLE T
WHERE ROW_NUM>1;

SELECT PARCELID, PROPERTYADDRESS, SALEPRICE, SALEDATE, LEGALREFERENCE, COUNT(*)
FROM NASHVILLEHOUSING
GROUP BY PARCELID, PROPERTYADDRESS, SALEPRICE, SALEDATE, LEGALREFERENCE
ORDER BY COUNT(*) DESC;

ALTER TABLE NASHVILLEHOUSING
ADD COUNT INT;

UPDATE NASHVILLEHOUSING N
SET COUNT = (SELECT ROW_NUMBER() OVER (
        PARTITION BY PARCELID
            , PROPERTYADDRESS
            , SALEPRICE
            , SALEDATE
            , LEGALREFERENCE 
        ORDER BY UNIQUEID_)
        FROM NASHVILLEHOUSING);

-------------------------------------------------------------------------------

-- Delete Unused Columns
ALTER TABLE NASHVILLEHOUSING
DROP COLUMN TAXDISTRICT;

ALTER TABLE NASHVILLEHOUSING
DROP COLUMN OWNERADDRESS;

ALTER TABLE NASHVILLEHOUSING
DROP COLUMN PROPERTYADDRESS;

ALTER TABLE NASHVILLEHOUSING
DROP COLUMN SALEDATE;

COMMIT;